on: pull_request

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn run smoke cjs 15.6.2
      - run: yarn run smoke esm 15.6.2
      - run: yarn run smoke cjs 16.7.0
      - run: yarn run smoke esm 16.7.0
      - run: yarn run smoke cjs 17.0.2
      - run: yarn run smoke esm 17.0.2
      - run: yarn run smoke cjs 18.0.0
      - run: yarn run smoke esm 18.0.0
      - run: yarn run smoke cjs 18.1.0
      - run: yarn run smoke esm 18.1.0
      - run: yarn run smoke cjs latest
      - run: yarn run smoke esm latest
      - run: yarn run smoke cjs next
      - run: yarn run smoke esm next

