on: pull_request

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.3'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn run smoke cjs 19.0.0
      - run: yarn run smoke esm 19.0.0
      - run: yarn run smoke cjs latest
      - run: yarn run smoke esm latest
      - run: yarn run smoke cjs next
      - run: yarn run smoke esm next

