name: Continuous Integration

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run:  yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run lint
      - run: yarn run flow
      - run: yarn run smoke cjs 15.6.2
      - run: yarn run smoke esm 15.6.2
      - run: yarn run smoke cjs 16.7.0
      - run: yarn run smoke esm 16.7.0
      - run: yarn run smoke cjs 17.0.1
      - run: yarn run smoke esm 17.0.1
      - run: yarn run smoke cjs latest
      - run: yarn run smoke esm latest
      - run: yarn run smoke cjs next
      - run: yarn run smoke esm next

