on: pull_request

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run typecheck
      - run: pnpm biome ci --colors=off
      - run: pnpm run build
      # FIXME: To be reactivated
      # - run: pnpm run smoke cjs 19.0.0
      # - run: pnpm run smoke esm 19.0.0
      # - run: pnpm run smoke cjs latest
      # - run: pnpm run smoke esm latest
      # - run: pnpm run smoke cjs next
      # - run: pnpm run smoke esm next
