on: pull_request

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test
      # FIXME: To be reactivated
      # - run: pnpm run lint
      - run: pnpm run tsc --noEmit
      # FIXME: To be reactivated (or not)
      # - run: pnpm run smoke cjs 15.6.2
      # - run: pnpm run smoke esm 15.6.2
      # - run: pnpm run smoke cjs 16.7.0
      # - run: pnpm run smoke esm 16.7.0
      # - run: pnpm run smoke cjs 17.0.1
      # - run: pnpm run smoke esm 17.0.1
      # - run: pnpm run smoke cjs latest
      # - run: pnpm run smoke esm latest
      # - run: pnpm run smoke cjs next
      # - run: pnpm run smoke esm next
